# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a4838f55742e510855b6a69a16ff9096ad1ebd5ecd0c08cd37162b31081203bbba8ca8d4992dc93c432cdc84b182dffb465539ed83f847a75acede30188eac6

test:
  secret_key_base: 87f5738de7e2258cc8d9706223f384a56bcd3a11b99d97e7871f9ed29ca650ed28f0b6b654fe99dd97df3fd6c1bec13a3a97aebfbadf55d62c6bb70f838a627d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
